name: Make check/distcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y texinfo libxml2-dev libxml2 openjdk-8-jdk
    - name: Fetch liblouis
      run: |
        wget https://github.com/liblouis/liblouis/archive/master.tar.gz
        tar -xf master.tar.gz
        ( cd liblouis-* && ./autogen.sh && ./configure && make && make install )
        ldconfig
    - name: Autogen && configure
      run: |
        ./autogen.sh
        ./configure
    - name: make
      run: make
    - name: make check
      run: make check
